[package]
name = "flotilla"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
itertools = "0.13.0"
k8s-openapi = { version = "0.23.0", features = ["latest"] }
kube = { version = "0.96.0", features = ["config", "client"] }
ratatui = "0.29.0"
tokio = { version = "1.41.0", features = ["full"] }
